---
swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: 0.0.1
  title: Bform API
  description:
    Bform API Beta

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /api/v1
schemes:
  # tip: remove http to make production-grade
  - http
  - https
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Users
    description: |
      User authentication and authorization

################################################################################
#                                    parameters                                #
################################################################################
parameters:
  id:
    name: id
    in: path
    description: ID
    type: integer
    required: true

################################################################################
#                              Paths                                           #
################################################################################
paths:
  /tokens:
    post:
      summary: create a new token using name and passowrd
      description:
        Used as login session for browser and for Mobile application as well.
      tags:
        - Users
      parameters:
        - name: auth
          in: body
          description: User auth information, name could be 'user name', 'email','mobile phone'
          required: true
          schema:
            $ref: '#/definitions/UserCredential'
      responses:
        201:
          description: A new token was created
          schema:
            $ref: '#/definitions/Token'
  /tokens/{token}:
    delete:
      summary: revoke a token
      parameters:
        - name: token
          in: path
          description: The token you want to revoke
          required: true
          type: string
      description: 
        You don't want to keep your login state on certain device, you can revoke them. Just like GitHub
      responses:
        200:
          description: OK
    
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  UserCredential:
    type: object
    properties:
      name:
        type: string
      password:
        type: string
        format: password
  Token:
    type: object
    properties:
      type:
        type: integer
      value:
        type: string
      issue:
        type: string
        format: date-time
      expire:
        type: string
        format: date-time
      device:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
